apiVersion: v1
kind: Service
metadata:
  name: apache
  # namespace: {{namespace}}
  labels:
    app: apache
    # branch: {{prefix}}
spec:
  selector:
    app: apache
  ports:
    - name: apache
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache
  # namespace: {{namespace}}
  labels:
    app: apache
    # branch: {{prefix}}
  annotations:
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.class: "apache"
    nginx.ingress.kubernetes.io/server-alias: "k8s.dcserver.ru"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "40M"
    nginx.ingress.kubernetes.io/proxy-body-size: "40M"
spec:
  rules:
    - host: "k8s.dcserver.ru"
      http:
        paths:
          - backend:
              service:
                name: apache
                port:
                  number: 80
            path: /
            pathType: Prefix

